apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-service-monitor
  namespace: prometheus-system
  labels:
    app: istiod
    release: prometheus
spec:
    namespaceSelector:
        matchNames:
        - istio-system
    selector:
        matchLabels:
            app: istiod
    endpoints:
    - port: http-monitoring
      path: '/stats/prometheus'
      interval: 15s
