apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-port-exposer
  labels:
    app: mssg-broker
spec:
  type: NodePort
  selector:
    app: mssg-broker
  ports:
    - name: broker-port
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30001
    - name: management-port
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30002