apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-persistent-volume
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/usr/share/elasticsearch/data"
